
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_MORE_POSTS = 'FETCH_MORE_POSTS';
export const FETCH_MORE_POSTS_SUCCESS = 'FETCH_MORE_POSTS_SUCCESS';
export const FETCH_MORE_POSTS_ERROR = 'FETCH_MORE_POSTS_ERROR';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const FETCH_MORE_COMMENTS_IN_POST = 'FETCH_MORE_COMMENTS_IN_POST';
export const FETCH_MORE_COMMENTS_IN_POST_SUCCESS = 'FETCH_MORE_COMMENTS_IN_POST_SUCCESS';
export const FETCH_MORE_COMMENTS_IN_POST_ERROR = 'FETCH_MORE_COMMENTS_IN_POST_ERROR';

export const POST_COMMENT = 'POST_COMMENT';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
